AllCops:
  TargetRubyVersion: 2.3

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: false
